### ISSUE TITLE
Install  does not work

### ISSUE THREAD

**Issue by denuoweb** [qtumproject/solar#20] opened 2019-04-11 06:12 UTC
go get -u github.com/qtumproject/solar/cli/solar

GIVES ME THIS ERROR
package github.com/ethereum/go-ethereum/crypto/sha3: cannot find package "github.com/ethereum/go-ethereum/crypto/sha3" in any of:
        /usr/lib/go-1.6/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOROOT)
        /home/mobileapi/gocode/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOPATH)
package context: unrecognized import path "context" (import path does not begin with hostname)

**Comment by denuoweb** [comment] 2019-04-11 06:13
please update the command or give me the commands I need instead of just telling me to downgrade geth because that doesn't help

**Comment by hayeah** [comment] 2019-04-16 03:48
this is fixed on master, was a dependency issue caused by eth internal cord reorganization.

**Closed by hayeah** 2019-04-16 03:48 UTC
